# Shell variables
# Generated by 'wal'
wallpaper='/home/shivam/Pictures/eos.png'

# Special
background='#000000'
foreground='#eddff0'
cursor='#eddff0'

# Colors
color0='#000000'
color1='#570F9D'
color2='#623ABE'
color3='#A32AFC'
color4='#B560DB'
color5='#BAA5D4'
color6='#E99FF9'
color7='#eddff0'
color8='#a59ca8'
color9='#570F9D'
color10='#623ABE'
color11='#A32AFC'
color12='#B560DB'
color13='#BAA5D4'
color14='#E99FF9'
color15='#eddff0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
