--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/shivam/Pictures/eos.png"

-- Special
background="#000000"
foreground="#eddff0"
cursor="#eddff0"

-- Colors
color0="#000000"
color1="#570F9D"
color2="#623ABE"
color3="#A32AFC"
color4="#B560DB"
color5="#BAA5D4"
color6="#E99FF9"
color7="#eddff0"
color8="#a59ca8"
color9="#570F9D"
color10="#623ABE"
color11="#A32AFC"
color12="#B560DB"
color13="#BAA5D4"
color14="#E99FF9"
color15="#eddff0"
